version: "2"

linters:
  default: standard
  enable:
    - bodyclose      # HTTP response body closed
    - errorlint      # Error wrapping issues
    - gosec          # Security issues
  settings:
    gosec:
      excludes:
        - G304  # File path from variable - false positives in internal code

exclusions:
  paths:
    - internal/api/generated  # oapi-codegen generated
    - internal/ws/generated   # protobuf generated
  presets:
    - common-false-positives
