apiVersion: 1

contactPoints:
  - orgId: 1
    name: ntfy
    receivers:
      - uid: ntfy
        type: webhook
        settings:
          url: $NTFY_SERVER/$NTFY_TOPIC
          httpMethod: POST
          authorization_scheme: Bearer
          authorization_credentials: $NTFY_TOKEN

policies:
  - orgId: 1
    receiver: ntfy
    group_by: [grafana_folder, alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
